---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


```{r echo=F}
pacman::p_load(tidyverse, huxtable, gt)

```


```{r echo=F}

hx <- pizzaplace |> 
   mutate(datetime = ymd_hms(paste(date, time)),
         date = ymd(date),
         year = year(datetime),
         month = month(datetime, label = TRUE, abbr = TRUE),
         day = month(datetime, label = TRUE, abbr = FALSE),
         hour = hour(datetime),
         day = case_when(hour <= 18 ~ 'Day', TRUE ~ 'Night')) |> 
  select(date, name, size, type, price, year, month, day) |> 
  filter(size %in% c('S', 'M', 'L')) |> 
  mutate(size = fct_relevel(size, 'S', 'M', 'L')) |> 
  count(day, type, size) |> 
  pivot_wider(names_from = size, values_from = n)
```


```{r echo=F}
hx |> huxtable() |> 
  set_text_color(2:5, 1, "purple") |> 
  set_text_color(6:9, 1, "orange") |> 
  set_italic(everywhere, c('S', 'M', 'L')) |> 
  set_bold(1, everywhere) |> 
  set_bottom_border(1, value = 2) |> 
  set_background_color(2:5, 2:5, '#eaa1f0') |> 
  set_background_color(6:9, 2:5, '#f7da99') |> 
  set_text_color(2:9, 2:5, "black")
```

```{r}
hx |> 
  as_hux() |> 
  theme_basic() |>  
  set_tb_padding(10) |> 
  set_contents(1, 1:2, c("DAY", "TYPE"))|> 
  #restack_across(rows = 5) |> 
  set_bottom_border(final(1), everywhere) |> 
  set_col_width(1:2, .3) |> 
  insert_row("", "", "SIZE", "", "", after = 0) |> 
  merge_cells(1, 3:5) |> 
  set_align(1, everywhere, "center") |> 
  set_bold(1:2, everywhere) 
```

